=== KDE/korganizer/knewstuff/data/knewstuff.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT knewstuff (stuff*)>
<!ELEMENT stuff (name,type,author,licence,summary*,version,release,releasedate,
                 preview*,payload*,rating?,downloads?)>

<!ELEMENT name (#PCDATA)>

<!ELEMENT type (#PCDATA)>

<!ELEMENT author (#PCDATA)>
  <!ATTLIST author email CDATA #REQUIRED>

<!ELEMENT licence (#PCDATA)>

<!ELEMENT summary (#PCDATA)>
  <!ATTLIST summary lang CDATA #REQUIRED>

<!ELEMENT version (#PCDATA)>

<!ELEMENT release (#PCDATA)>

<!ELEMENT releasedate (#PCDATA)>

<!ELEMENT url (#PCDATA)>

<!ELEMENT preview (#PCDATA)>
  <!ATTLIST preview lang CDATA #REQUIRED>

<!ELEMENT payload (#PCDATA)>
  <!ATTLIST payload lang CDATA #REQUIRED>

<!ELEMENT rating (#PCDATA)>

<!ELEMENT downloads (#PCDATA)>

=== KDE/korganizer/knewstuff/data/knewstuff.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE knewstuff SYSTEM "knewstuff.dtd">
<knewstuff>
  <stuff>
    <name>worldcup2002</name>
    <type>korganizer/calendar</type>
    <author email="schumacher@kde.org">Cornelius Schumacher</author>
    <licence>GPL</licence>
    <summary lang="en">Soccer world cup 2002</summary>
    <version>1.0</version>
    <release>1</release>
    <releasedate>2002-06-19</releasedate>
    <preview lang="en"></preview>
    <payload lang="en">http://korganizer.kde.org/knewstuff/korganizer/calendar/worldcup2002.ics</payload>
    <rating>5</rating>
    <downloads>0</downloads>
  </stuff>
  <stuff>
    <name>f12002</name>
    <type>korganizer/calendar</type>
    <author email="schumacher@kde.org">Cornelius Schumacher</author>
    <licence>GPL</licence>
    <summary lang="en">Formula One championship 2002</summary>
    <version>1.0</version>
    <release>1</release>
    <releasedate>2002-06-12</releasedate>
    <payload lang="en">http://korganizer.kde.org/knewstuff/korganizer/calendar/f12002.ics</payload>
    <rating>3</rating>
    <downloads>2</downloads>
  </stuff>
  <stuff>
    <name>kde3.1</name>
    <type>korganizer/calendar</type>
    <author email="schumacher@kde.org">Cornelius Schumacher</author>
    <licence>GPL</licence>
    <summary lang="en" >KDE 3.1 release plan</summary>
    <version>1.0</version>
    <release>1</release>
    <releasedate>2002-06-18</releasedate>
    <preview lang="en" >http://developer.kde.org/development-versions/kde-3.1-release-plan.html</preview>
    <payload lang="en" >http://korganizer.kde.org/knewstuff/korganizer/calendar/kde3.1.ics</payload>
    <rating>0</rating>
    <downloads>0</downloads>
  </stuff>
</knewstuff>
